# åšå®¢æ ‡é¢˜
navbar:
  blog_title: ""

# å±•ç¤º PV ä¸ UV ç»Ÿè®¡
footer:
  statistics:
    enable: true
    source: "busuanzi"  # å¯é€‰ leancloud | busuanzi  æ ¹æ®è‡ªå·±éœ€æ±‚é€‰æ‹©
    pv_format: "æ€»è®¿é—®é‡ {} æ¬¡"  # æ˜¾ç¤ºçš„æ–‡æœ¬ï¼Œ{}æ˜¯æ•°å­—çš„å ä½ç¬¦ï¼ˆå¿…é¡»åŒ…å«)ï¼Œä¸‹åŒ
    uv_format: "æ€»è®¿å®¢æ•° {} äºº"

# æš—è‰²æ¨¡å¼
dark_mode:
  enable: true
  default: auto

# Slogan(æ‰“å­—æœº)
index:
  slogan:
    enable: true
    text: ğŸŒŠçœ‹è¿‡å¤§æµ·çš„äººä¸ä¼šå¿˜è®°æµ·çš„å¹¿é˜”ğŸŒŠ
    api:
      enable: true
      url: "https://v1.hitokoto.cn/?c=a&c=c&c=d&c=i&c=k&c=l"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]