# åšå®¢æ ‡é¢˜
navbar:
  blog_title: ""

  # å¯¼èˆªæ èœå•ï¼Œå¯è‡ªè¡Œå¢å‡ï¼Œkey ç”¨æ¥å…³è” languages/*.ymlï¼Œå¦‚ä¸å­˜åœ¨å…³è”åˆ™æ˜¾ç¤º key æœ¬èº«çš„å€¼ï¼›icon æ˜¯ css classï¼Œå¯ä»¥çœç•¥ï¼›å¢åŠ  name å¯ä»¥å¼ºåˆ¶æ˜¾ç¤ºæŒ‡å®šåç§°
  # Navigation bar menu. `key` is used to associate languages/*.yml. If there is no association, the value of `key` itself will be displayed; if `icon` is a css class, it can be omitted; adding `name` can force the display of the specified name
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }  
    - { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }

# å±•ç¤º PV ä¸ UV ç»Ÿè®¡
footer:
  statistics:
    enable: true
    source: "busuanzi"  # å¯é€‰ leancloud | busuanzi  æ ¹æ®è‡ªå·±éœ€æ±‚é€‰æ‹©
    pv_format: "æ€»è®¿é—®é‡ {} æ¬¡"  # æ˜¾ç¤ºçš„æ–‡æœ¬ï¼Œ{}æ˜¯æ•°å­—çš„å ä½ç¬¦ï¼ˆå¿…é¡»åŒ…å«)ï¼Œä¸‹åŒ
    uv_format: "æ€»è®¿å®¢æ•° {} äºº"

# æš—è‰²æ¨¡å¼
dark_mode:
  enable: true
  default: auto

# Slogan(æ‰“å­—æœº)
index:
  slogan:
    enable: true
    text: ğŸŒŠçœ‹è¿‡å¤§æµ·çš„äººä¸ä¼šå¿˜è®°æµ·çš„å¹¿é˜”ğŸŒŠ
    api:
      enable: true
      url: "https://v1.hitokoto.cn/?c=a&c=c&c=d&c=i&c=k&c=l"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]

#---------------------------
# å…³äºé¡µ
# About Page
#---------------------------
about:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  avatar: /img/avatar.png
  name: "Fluid"
  intro: "An elegant theme for Hexo"
  # æ›´å¤šå›¾æ ‡å¯ä» https://hexo.fluid-dev.com/docs/icon/ æŸ¥æ‰¾ï¼Œ`class` ä»£è¡¨å›¾æ ‡çš„ css classï¼Œæ·»åŠ  `qrcode` åï¼Œå›¾æ ‡ä¸å†æ˜¯é“¾æ¥è€Œæ˜¯æ‚¬æµ®äºŒç»´ç 
  # More icons can be found from https://hexo.fluid-dev.com/docs/en/icon/  `class` is the css class of the icon. If adding `qrcode`, The icon is no longer a link, but a hovering QR code
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/wang551/", tip: "GitHub" }
    - { class: "iconfont icon-mail", link: "https://github.com/wang551/", tip: "GitHub" }   
    # - { class: "iconfont icon-douban-fill", link: "https://douban.com", tip: "è±†ç“£" }
    # - { class: "iconfont icon-wechat-fill", qrcode: "/img/favicon.png" }

#---------------------------
# å‹é“¾é¡µ
# Links Page
#---------------------------
links:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  # å‹é“¾çš„æˆå‘˜é¡¹
  # Member item of page
  items:
    - {
      title: "å¼ ä½œä¿Š's çªç‚¹",
      intro: "longlong's çª",
      link: "https://zhangzuojun1127.github.io/",
      # avatar: "/img/favicon.png",
      avatar: "https://zhangzuojun1127.github.io/medias/logo.png"
    }
  default_avatar: /img/avatar.png
